### ISSUE TITLE
Problem in files annotator2.zip and annotator3.zip

### ISSUE THREAD

**Issue by verissimomanoel** [JAugusto97/ToLD-Br#1]
Dear,
I'm trying to replicate your experiments, and I think you have a problem with your data file in the experiments folder. When we extracted the file annotator2.zip was created a folder 3annotator, and when we extracted the file annotator2.zip, the same folder was created. In my opinion, the files annotator2.zip and annotator3.zip have the same content.

**Comment by joaoaleite** [comment]
Hey @verissimomanoel thanks for noticing, I've found the original files and updated them!
